
import { Product } from './types';
import { 
  SHILAJIT_IMAGE_URL, 
  ALMONDS_IMAGE_URL, 
  DRIED_APRICOT_IMAGE_URL,
  ORGANIC_SHILAJIT_20G_URL,
  ORGANIC_SHILAJIT_3G_URL,
  PURE_SHILAJIT_20G_URL,
  SHILAJIT_10G_URL
} from './assets';

export const MOCK_PRODUCTS: Product[] = [
  {
    _id: '1',
    name: 'Himalayan Shilajit Resin (20g)',
    image: ORGANIC_SHILAJIT_20G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: '100% pure, lab-tested Shilajit resin harvested from the highest altitudes of the Himalayas. A potent source of fulvic acid and over 84 essential minerals.',
    price: 2999,
    countInStock: 15,
    rating: 4.8,
    numReviews: 3,
    reviews: [
      { _id: 'r1', name: 'Ali Khan', rating: 5, comment: 'Amazing quality! Felt the difference in energy within days.', createdAt: '2023-10-15T10:00:00Z' },
      { _id: 'r2', name: 'Sara Ahmed', rating: 5, comment: 'Packaging was great and the resin is very pure.', createdAt: '2023-10-18T14:30:00Z' },
      { _id: 'r3', name: 'John Doe', rating: 4, comment: 'Good product, but delivery took a bit longer than expected.', createdAt: '2023-11-02T09:15:00Z' },
    ]
  },
  {
    _id: '1b',
    name: 'Himalayan Shilajit Resin (10g)',
    image: SHILAJIT_10G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: '100% pure, lab-tested Shilajit resin harvested from the highest altitudes of the Himalayas. Perfect starter size — a potent source of fulvic acid and over 84 essential minerals.',
    price: 1900,
    countInStock: 20,
    rating: 4.8,
    numReviews: 2,
    reviews: [
      { _id: 'r1b1', name: 'Usman Ali', rating: 5, comment: 'Great starter pack! Perfect quality.', createdAt: '2024-01-10T10:00:00Z' },
      { _id: 'r1b2', name: 'Maria Khan', rating: 5, comment: 'Excellent quality for the price.', createdAt: '2024-02-05T14:30:00Z' },
    ]
  },
  {
    _id: '2',
    name: 'Organic Apricot Kernel Oil (120ml)',
    image: 'https://picsum.photos/id/1025/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: 'Cold-pressed from the finest apricot kernels of Skardu Valley. Rich in Vitamin E and antioxidants, perfect for skin and hair nourishment.',
    price: 1200,
    countInStock: 30,
    rating: 4.5,
    numReviews: 2,
    reviews: [
        { _id: 'r4', name: 'Fatima', rating: 5, comment: 'My skin loves this oil. So moisturizing!', createdAt: '2023-09-20T08:00:00Z' },
        { _id: 'r5', name: 'Zainab', rating: 4, comment: 'Use it for my hair, works wonders.', createdAt: '2023-10-05T16:45:00Z' },
    ]
  },
  {
    _id: '3',
    name: 'Sun-Dried Organic Apricots (500g)',
    image: DRIED_APRICOT_IMAGE_URL,
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'Naturally sweet and chewy sun-dried apricots from Gilgit-Baltistan. No added sugar or preservatives. A healthy and delicious snack.',
    price: 950,
    countInStock: 50,
    rating: 4.7,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '4',
    name: 'Wild Forest Honey (250g)',
    image: 'https://picsum.photos/id/1068/400/400',
    brand: 'Skardu Organics',
    category: 'Natural Foods',
    description: 'Raw and unfiltered honey sourced from the wild forests of the Karakoram range. Possesses unique floral notes and immense health benefits.',
    price: 1500,
    countInStock: 25,
    rating: 4.9,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '5',
    name: 'Organic Almonds (Kaghazi Badam) (500g)',
    image: ALMONDS_IMAGE_URL,
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'Premium quality paper-thin shell almonds (Kaghazi Badam) that are easy to crack and delicious to eat. Packed with nutrients.',
    price: 1800,
    countInStock: 40,
    rating: 4.6,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '6',
    name: 'Sea Buckthorn Oil (30ml)',
    image: 'https://picsum.photos/id/312/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: 'A powerhouse of Omega-7, vitamins, and antioxidants. Our Sea Buckthorn oil is perfect for rejuvenating skin and promoting internal health.',
    price: 2200,
    countInStock: 18,
    rating: 4.8,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '7',
    name: 'Organic Walnuts (Akhrot) (500g)',
    image: 'https://picsum.photos/id/431/400/400',
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'Fresh and crunchy walnuts from the valleys of Skardu. An excellent source of Omega-3 fatty acids and a great brain food.',
    price: 1600,
    countInStock: 35,
    rating: 4.5,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '8',
    name: 'Advanced Shilajit Gold Capsules (60 count)',
    image: PURE_SHILAJIT_20G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: 'Experience the benefits of Shilajit in a convenient capsule form, enriched with other Ayurvedic herbs for enhanced vitality and performance.',
    price: 5500,
    countInStock: 10,
    rating: 4.9,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '9',
    name: 'Pure Shilajit Drops (30ml)',
    image: ORGANIC_SHILAJIT_3G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: 'Convenient and easy-to-use Shilajit drops. A liquid supplement for quick absorption and daily wellness.',
    price: 3800,
    countInStock: 22,
    rating: 4.7,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '10',
    name: 'Shilajit with Ashwagandha',
    image: PURE_SHILAJIT_20G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: 'A powerful blend of Himalayan Shilajit and Ashwagandha root extract to combat stress and boost energy levels.',
    price: 4900,
    countInStock: 12,
    rating: 4.9,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '11',
    name: 'Sun-Dried Raw Shilajit Stone (50g)',
    image: PURE_SHILAJIT_20G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: 'Raw, sun-dried Shilajit in its most natural form. For the purists who prefer traditional preparation methods.',
    price: 6000,
    countInStock: 8,
    rating: 4.6,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '12',
    name: 'Shilajit Power Mix with Herbs (30g)',
    image: ORGANIC_SHILAJIT_20G_URL,
    brand: 'Skardu Organics',
    category: 'Shilajit',
    description: 'A potent mix of Shilajit resin with a blend of traditional herbs for maximum vitality and strength.',
    price: 5200,
    countInStock: 14,
    rating: 4.8,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '13',
    name: 'Cold-Pressed Walnut Oil (120ml)',
    image: 'https://picsum.photos/id/15/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: '100% pure cold-pressed walnut oil. Rich in Omega-3, it is excellent for brain health and as a salad dressing.',
    price: 1800,
    countInStock: 25,
    rating: 4.7,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '14',
    name: 'Organic Black Seed Oil (100ml)',
    image: 'https://picsum.photos/id/16/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: 'Known as "the cure for everything except death," our black seed oil is cold-pressed to preserve its powerful compounds.',
    price: 2500,
    countInStock: 20,
    rating: 4.9,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '15',
    name: 'Pure Organic Castor Oil (150ml)',
    image: 'https://picsum.photos/id/17/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: 'A versatile oil known for promoting hair growth and nourishing the skin. Hexane-free and cold-pressed.',
    price: 900,
    countInStock: 40,
    rating: 4.5,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '16',
    name: 'Relaxing Apricot Massage Oil (200ml)',
    image: 'https://picsum.photos/id/18/400/400',
    brand: 'Skardu Organics',
    category: 'Organic Oils',
    description: 'A light, non-greasy massage oil made from pure apricot oil and infused with calming essential oils.',
    price: 1500,
    countInStock: 30,
    rating: 4.6,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '17',
    name: 'Organic Dried Figs (Anjeer) (500g)',
    image: 'https://picsum.photos/id/19/400/400',
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'Naturally sweet and packed with fiber, our organic dried figs are a perfect healthy treat.',
    price: 2100,
    countInStock: 33,
    rating: 4.8,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '18',
    name: 'Organic Pine Nuts (Chilgoza) (250g)',
    image: 'https://picsum.photos/id/21/400/400',
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'A delicacy from the high-altitude forests of Gilgit-Baltistan, these pine nuts are rich in flavor and nutrients.',
    price: 3500,
    countInStock: 15,
    rating: 4.9,
    numReviews: 0,
    reviews: []
  },
  {
    _id: '19',
    name: 'Dried Mulberries (Shahtoot) (400g)',
    image: 'https://picsum.photos/id/22/400/400',
    brand: 'Skardu Organics',
    category: 'Dry Fruits',
    description: 'Sun-dried white mulberries, a naturally sweet superfood packed with iron, vitamin C, and antioxidants.',
    price: 1100,
    countInStock: 45,
    rating: 4.7,
    numReviews: 0,
    reviews: []
  },
];
